[project]
name = "eportfolio-prot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask-login>=0.6.3",
    "flask-wtf>=1.2.1",
    "flask>=3.0.3",
]
